### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by the1mills** [PauliBuccini/meteor-linkedin#1]
Hi Pauli

Can you create a quick example of how to configure a login with LinkedIn. It's easy with Twitter, but after running

meteor add pauli:linkedin

I don't know what to do next, thanks

**Comment by PoBuchi** [comment]
Sry @the1mills  for super late reply, but if you still wondering configuration is identical to Twitter or Facebook

```
ServiceConfiguration.configurations.insert({
  service: "linkedin",
  clientId: "yourclientId",
  secret: "yoursecret"
})

```
