### ISSUE TITLE
Multiple LinkedIn API subdomains

### ISSUE THREAD

**Issue by leoc** [PauliBuccini/meteor-linkedin#5]
Hello, first let me thank you for this package.

I have a question about the API domain. You use `www.linkedin.com` and `api.linkedin.com` are they the same? I am creating a stubbing package for linkedin. Thus it would be great to use one subdomain consistently.

Thanks!

**Comment by PoBuchi** [comment]
Hi @leoc, 
did you took a look about current API, if two separate domains still needed?

**Comment by leoc** [comment]
As far as I know, we only need www.linkedin.com for the authorization call to the LinkedIn Login form to keep the current LinkedIn-Session of the user. All other calls should work over api.linkedin.com.
